### ISSUE TITLE
Not running on Windows 11(I think?)

### ISSUE THREAD

**Issue by ghost** [brentbatch/Advanced-Blueprint-Tool-V2#16]
When I launch "StandaloneWindows64.exe" it asks for Scrap Mechanic path. When I give it Scrap Mechanic path(D:\SteamLibrary\steamapps\common\Scrap Mechanic), It starts to not respond

https://user-images.githubusercontent.com/68902211/177004059-12b94f94-8f71-4340-8b23-a4a16ce84131.mp4

**Comment by Bruh2801** [comment]
can confirm even on windows 10,try downloading earlier versions for now.

**Comment by Nokodev-programming** [comment]
The problem is that. This tool is no longer updated, Soo your out of luck.
